# .github/dependabot.yml
# Basic set up for Dependabot alerts and security updates

version: 2
updates:

  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    # Look for `go.mod` file in the root directory
    directory: "/"
    # Check for updates daily (weekly is also common)
    schedule:
      interval: "daily"
    # Optional: Add assignees for the created PRs
    # assignees:
    #  - "your-github-username"
    # Optional: Add reviewers
    # reviewers:
    #  - "reviewer-username"
    # Optional: Add labels
    # labels:
    #  - "dependencies"
    #  - "golang"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for workflow files in the default directory
    directory: "/"
    schedule:
      interval: "daily"
    # Optional: Add assignees
    # assignees:
    #   - "your-github-username"

